# Generated by Django 5.2 on 2025-04-23 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_student_user_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mainTeacher',
        ),
    ]
